<a href="https://colab.research.google.com/github/apollo13092808/pytorch-docs/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
a = [[1, 2], [3, 4]]
print(a)
print(type(a))
print()

t = torch.tensor(a)
print(t)
print(type(t))

[[1, 2], [3, 4]]
<class 'list'>

tensor([[1, 2],
        [3, 4]])
<class 'torch.Tensor'>


In [3]:
a = [[1, 2], [3, 4]]

n = np.array(a)
print(n)
print(type(n))
print()

t = torch.from_numpy(n)
print(t)
print(type(t))

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>

tensor([[1, 2],
        [3, 4]])
<class 'torch.Tensor'>


In [4]:
print(torch.ones_like(torch.tensor(a)))

tensor([[1, 1],
        [1, 1]])


In [5]:
print(torch.rand_like(torch.tensor(a), dtype=torch.float))

tensor([[0.2911, 0.3247],
        [0.0309, 0.2352]])


In [6]:
t = torch.rand(3, 4)
print(t)

tensor([[0.1015, 0.4887, 0.8793, 0.9093],
        [0.8525, 0.5788, 0.7389, 0.3574],
        [0.2405, 0.4634, 0.5032, 0.2874]])


In [7]:
print(f" Shape: {t.shape}")
print(f" Dtype: {t.dtype}")
print(f"Device: {t.device}")

 Shape: torch.Size([3, 4])
 Dtype: torch.float32
Device: cpu


In [8]:
if torch.cuda.is_available():
    t = t.to("cuda")

In [9]:
t = torch.tensor([[ 1,  2,  3,  4],
                  [ 5,  6,  7,  8],
                  [ 9, 10, 11, 12],
                  [13, 14, 15, 16]])

print(t)
print(f"\nFirst row: {t[0]}")
print(f"\nFirst column: {t[:, 0]}")
print(f"\nLast row: {t[..., -1]}")

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])

First row: tensor([1, 2, 3, 4])

First column: tensor([ 1,  5,  9, 13])

Last row: tensor([ 4,  8, 12, 16])


In [10]:
t = torch.randn(2, 3)
print(t)

tensor([[ 1.2082, -0.9605, -0.7607],
        [ 1.7617, -1.1731,  0.0089]])


In [11]:
print(torch.cat(tensors=[t, t], dim=1))

tensor([[ 1.2082, -0.9605, -0.7607,  1.2082, -0.9605, -0.7607],
        [ 1.7617, -1.1731,  0.0089,  1.7617, -1.1731,  0.0089]])


In [12]:
print(torch.cat(tensors=[t, t, t], dim=0))

tensor([[ 1.2082, -0.9605, -0.7607],
        [ 1.7617, -1.1731,  0.0089],
        [ 1.2082, -0.9605, -0.7607],
        [ 1.7617, -1.1731,  0.0089],
        [ 1.2082, -0.9605, -0.7607],
        [ 1.7617, -1.1731,  0.0089]])


In [14]:
tensor = torch.randn(4, 4)
print(tensor)

tensor([[ 0.3662, -0.4579,  0.0250,  0.6168],
        [ 1.1122,  1.1102, -0.5454,  1.0692],
        [-0.2610,  0.1941,  0.4885,  0.6939],
        [-1.0462, -0.1185,  2.5004, -1.7972]])


In [16]:
y1 = tensor @ tensor.T
print(y1)

tensor([[ 0.7248,  0.5447,  0.2558, -1.3748],
        [ 0.5447,  3.9104,  0.4007, -4.5805],
        [ 0.2558,  0.4007,  0.8260,  0.2243],
        [-1.3748, -4.5805,  0.2243, 10.5907]])


In [17]:
y2 = tensor.matmul(tensor.T)
print(y2)

tensor([[ 0.7248,  0.5447,  0.2558, -1.3748],
        [ 0.5447,  3.9104,  0.4007, -4.5805],
        [ 0.2558,  0.4007,  0.8260,  0.2243],
        [-1.3748, -4.5805,  0.2243, 10.5907]])


In [18]:
y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)
print(y3)

tensor([[ 0.7248,  0.5447,  0.2558, -1.3748],
        [ 0.5447,  3.9104,  0.4007, -4.5805],
        [ 0.2558,  0.4007,  0.8260,  0.2243],
        [-1.3748, -4.5805,  0.2243, 10.5907]])


In [19]:
z1 = tensor * tensor
z2 = tensor.matmul(tensor)

z3 = torch.randn_like(tensor)
print(torch.mul(tensor, tensor, out=z3))

tensor([[1.3409e-01, 2.0969e-01, 6.2652e-04, 3.8043e-01],
        [1.2371e+00, 1.2326e+00, 2.9745e-01, 1.1432e+00],
        [6.8134e-02, 3.7663e-02, 2.3861e-01, 4.8156e-01],
        [1.0945e+00, 1.4042e-02, 6.2521e+00, 3.2300e+00]])


In [20]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

3.950345754623413 <class 'float'>
